### ISSUE TITLE
Permission to publish a port that is based on graphene-django-optimizer

### ISSUE THREAD

**Issue by cbergmiller** [tfoxy/graphene-django-optimizer#78]
Hello, i made a port of graphene-django-optimizer that is intended for use with strawberry-graphql:
https://github.com/energy-efficiency/strawberry-django-optimizer

I would like to ask for permission to make it available under MIT license. I also would like to puplish it on PyPi.
I already added a link to graphene-django-optimizer in the documentation. Is there anything else i should do to accredit the authors of graphene-django-optimizer?

**Comment by tfoxy** [comment]
Hi @cbergmiller ! Glad that this codebase was helpful for you to integrate with strawberry. Not a lawyer, but googled and found:

https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370

It seems that adding author name to the license would be enough. At least from my side, I'm ok with that. MIT license was applied to this repo because of the popularity and because I want people using it / forking it as they see fit.

This raises me the question if I should include the people that contributed to this repo and how to add them (real names, GH names, link to GH contributors?). Tried to do a quick search but couldn't find a conclusive solution.
